version: "3"
services:
  ubuntu:
    volumes:
      - ../:/workspace:cached
      - ~/.gitconfig:/etc/gitconfig
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: .
      dockerfile: Dockerfile
